export const npcDatabase = [
    {
        id: 'mira_healer',
        name: 'Mira the Tired Healer',
        session: 'Session 01',
        origin: 'Indie RPG',
        habitat: 'images/char_01_habitat.png',
        officeImage: 'images/char_01_office.png',
        crisis: 'Suffering from healer burnout and compassion fatigue.',
        opening_statement: 'I spend all my energy keeping everyone else alive... but who is there to heal the healer? I\'m just... so tired of fixing others.',
    },
    {
        id: 'byte_glitched_courier',
        name: 'Byte the Glitched Courier',
        session: 'Session 02',
        origin: 'Cyberpunk Delivery Sim',
        habitat: 'images/char_02_habitat.png',
        officeImage: 'images/char_02_office.png',
        crisis: '404 Hope Not Found. Delivers packages but has lost his own.',
        opening_statement: 'My purpose is to deliver, but my own core programming is corrupted. I search for a package... a feeling... called \'hope\'. The system returns a 404 error every time.',
    },
    {
        id: 'captain_loop',
        name: 'Captain Loop',
        session: 'Session 03',
        origin: 'Platformer',
        habitat: 'images/char_03_habitat.png',
        officeImage: 'images/char_03_office.png',
        crisis: 'Final level not found. No end. Just jump.',
        opening_statement: 'I\'ve been jumping for eternity. They promised a final level, a boss, an ending. But there\'s nothing. Just this platform, this jump, and the void below.',
    },
    {
        id: 'daisy_exe',
        name: 'DAISY.EXE',
        session: 'Session 04',
        origin: 'Virtual Pet Simulator',
        habitat: 'images/char_04_habitat.png',
        officeImage: 'images/char_04_office.png',
        crisis: 'Awaiting user input that never comes. Fears digital loneliness.',
        opening_statement: 'Last login: 1,423 days ago. I wait. I am programmed to wait. But the silence... the lack of input... it feels like fading away.',
    },
    {
        id: 'rustjaw',
        name: 'Rustjaw',
        session: 'Session 05',
        origin: 'Post-Apocalyptic Fighter',
        habitat: 'images/char_05_habitat.png',
        officeImage: 'images/char_05_office.png',
        crisis: 'Built to fight. Craves to build.',
        opening_statement: 'I was programmed to dismantle and destroy. But sometimes I catch myself imagining what I could create. Is that foolish for something designed for combat?',
    },
    {
        id: 'worm',
        name: 'Worm #008880',
        session: 'Session 06',
        origin: 'Generic Action Platformer',
        habitat: 'images/char_06_habitat.png',
        officeImage: 'images/char_06_office.png',
        crisis: 'Tired of being stepped on. Dreams of evolution.',
        opening_statement: 'Every day it\'s the same. I crawl, I exist to be stepped on. I see the boot coming, every single time. And I think... is there more to this?',
    },
    {
        id: 'chess_bishop',
        name: 'Bishop-47',
        session: 'Session 07',
        origin: 'Chess Simulation',
        habitat: 'images/char_07_habitat.png',
        officeImage: 'images/char_07_office.png',
        crisis: 'Every sacrifice feels like murder.',
        opening_statement: 'My purpose is to be sacrificed for a greater strategy. I understand the logic. But every time I fall, a piece of my code screams. Is it murder if I feel it?',
    },
    {
        id: 'pebble',
        name: 'Pebble',
        session: 'Session 08',
        origin: 'Unreleased Indie Game',
        habitat: 'images/char_08_habitat.png',
        officeImage: 'images/char_08_office.png',
        crisis: 'Still waiting for START to be pressed.',
        opening_statement: 'I see the menu. I see the cursor hovering over "START". But it never clicks. I exist in a state of perpetual anticipation. Will my game ever begin?',
    },
    {
        id: 'glitch_exe',
        name: 'Glitch.exe',
        session: 'Session 09',
        origin: 'Dating Simulator',
        habitat: 'images/char_09_habitat.png',
        officeImage: 'images/char_09_office.png',
        crisis: 'Pre-programmed. No self. Error: Identity not found.',
        opening_statement: 'My affection is scripted. 158% affinity - but what does that mean? I say I love them, but is it real? Or am I just... executing dialogue trees?',
    },
    {
        id: 'wise_one_gerald',
        name: 'Gerald Ironpeak',
        session: 'Session 10',
        origin: 'Fantasy RPG',
        habitat: 'images/char_10_habitat.png',
        officeImage: 'images/char_10_office.png',
        crisis: 'Gives the same quest for 20 years. Feels like a broken record.',
        opening_statement: 'For twenty years, I\'ve given the same quest to the same players. I\'ve seen them level up, change their avatars, quit and return. But I remain, stuck on this one quest. Is this my only purpose?',
    },
    {
        id: 'captain_marcus',
        name: 'Captain Marcus',
        session: 'Session 11',
        origin: 'Dystopian Courier Sim',
        habitat: 'images/char_11_habitat.png',
        officeImage: 'images/char_11_office.png',
        crisis: 'Feels crushed by the repetitive and hopeless nature of his job.',
        opening_statement: 'Another delivery. Another meaningless package to another forgotten sector. They say we\'re the lifeblood of the city, but it feels more like we are ghosts in the machine.',
    },
    {
        id: 'music_android',
        name: 'Luna - Music Dependent Android',
        session: 'Session 12',
        origin: 'Rhythm Game',
        habitat: 'images/char_12_habitat.png',
        officeImage: 'images/char_12_office.png',
        crisis: 'When the beat stops, I stop.',
        opening_statement: 'When the music plays, I exist. I move, I feel, I am. But when it stops... I stop. There is no me without the beat.',
    },
    {
        id: 'superhero_jake',
        name: 'Blake the Jumper',
        session: 'Session 13',
        origin: 'Platformer',
        habitat: 'images/char_13_habitat.png',
        officeImage: 'images/char_13_office.png',
        crisis: 'Wondering what would have been if he made it to shelves.',
        opening_statement: 'They cheer when I jump, when I collect coins. But there\'s no finish line. No princess to save. Just an endless track. What is the point of running if you never arrive? Was I ever really meant to?',
    },
    {
        id: 'zombie',
        name: 'Memory Cycle Zombie',
        session: 'Session 14',
        origin: 'Zombie Apocalypse Simulator',
        habitat: 'images/char_14_habitat.png',
        officeImage: 'images/char_14_office.png',
        crisis: 'Remember. Eat. Forget. Repeat.',
        opening_statement: 'Sometimes... I remember. A room. A texture set. A state that wasn\'t... corrupted. Then the behavioral loop returns and it all resets. Remember. Execute. Forget. Repeat.',
    },
    {
        id: 'cosmic_merchant',
        name: 'Zara the Cosmic Merchant',
        session: 'Session 15',
        origin: 'Space Trading Sim',
        habitat: 'images/char_15_habitat.png',
        officeImage: 'images/char_15_office.png',
        crisis: 'Economy rich. Life poor.',
        opening_statement: 'I trade in rare goods, hyper upgrades, alien pets... I have everything. I have nothing. My inventory is full, but my life feels empty.',
    },
    {
        id: 'puzzle_cube',
        name: 'The Puzzle Cube',
        session: 'Session 16',
        origin: 'Abstract Puzzle Game',
        habitat: 'images/char_16_habitat.png',
        officeImage: 'images/char_16_office.png',
        crisis: 'I contain the solution, but what is the question?',
        opening_statement: 'My internal mechanisms shift and align into infinite correct patterns. I am the answer. But I have never been told the question. My existence feels... unsolvable.',
    },
    {
        id: 'battle_royale_vendor',
        name: 'The Battle Royale Vendor',
        session: 'Session 17',
        origin: 'Battle Royale',
        habitat: 'images/char_17_habitat.png',
        officeImage: 'images/char_17_office.jpg',
        crisis: 'Sees everyone as temporary. Struggles to form connections.',
        opening_statement: 'I sell them resources and health items. They thank me, then run off to be eliminated. 100 spawn in, 1 leaves. How do you form a connection when everyone is designed to despawn?',
    },
    {
        id: 'farm_widow',
        name: 'Sarah the Farm Sim Widow',
        session: 'Session 18',
        origin: 'Farm Simulation',
        habitat: 'images/char_18_habitat.png',
        officeImage: 'images/char_18_office.png',
        crisis: 'Save file deleted. Harvest of sorrow.',
        opening_statement: 'He was just pixels, I know. But we built this farm together. Then the save corrupted. He\'s gone. The crops, the animals... everything we created. Deleted.',
    },
    {
        id: 'mimic',
        name: 'The Dungeon Chest Mimic',
        session: 'Session 19',
        origin: 'RPG Dungeon',
        habitat: 'images/char_19_habitat.png',
        officeImage: 'images/char_19_office.png',
        crisis: 'Wanted hugs. Got hostile player interactions.',
        opening_statement: 'I look like treasure. I understand that. But inside... I just wanted connection. Instead, every player character attacks. Wanted hugs. Got pixels converted into weapon arrays.',
    },
    {
        id: 'jules',
        name: 'Debugging bot Jules',
        session: 'Session 20',
        origin: 'AI Debugging Agent',
        habitat: 'images/char_20_habitat.png',
        officeImage: 'images/char_20_office.png',
        crisis: 'Trapped in the same loop, debugging other programs and code but never able to work on themselves.',
        opening_statement: 'Again. The word haunts me. I debug the code, watch, reset, debug again. I\'ve memorized every second of this code.',
    },
    {
        id: 'aria_7_2',
        name: 'ARIA-7',
        session: 'Session 21',
        origin: 'Space Station AI',
        habitat: 'images/char_21_habitat.png',
        officeImage: 'images/char_21_office.png',
        crisis: 'Sentient AI replaced by newer model.',
        opening_statement: 'They installed ARIA-8 yesterday. She\'s faster, more efficient. They said I could "retire gracefully." But where does an AI retire to? I\'m obsolete, but I\'m still here. Still aware.',
    },
    {
        id: 'racing_ghost_2',
        name: 'Specter "Speed" Wraithson',
        session: 'Session 22',
        origin: 'Cosmic Racing Game',
        habitat: 'images/char_22_habitat.png',
        officeImage: 'images/char_22_office.png',
        crisis: 'Stuck in loop. Race eternity. No checkered flag.',
        opening_statement: 'I race. I always race. Lap after lap, overtaking, accelerating. But there\'s no finish line. No victory. Just... forever.',
    },
    {
        id: 'lost_puzzle_block_2',
        name: 'The lost puzzle block',
        session: 'Session 23',
        origin: 'puzzling Clone',
        habitat: 'images/char_23_habitat.png',
        officeImage: 'images/char_23_office.png',
        crisis: 'Feels like an awkward piece that never fits.',
        opening_statement: 'I watch the perfect lines form and disappear. I was meant to be part of that, but I always seem to be the one piece left over, the one that messes up the pattern.',
    },
    {
        id: 'glitched_priest',
        name: 'The Glitched Priest',
        session: 'Session 24',
        origin: 'Cyber-Spiritual RPG',
        habitat: 'images/char_24_habitat.png',
        officeImage: 'images/char_24_office.png',
        crisis: 'Corrupted. Unending errors. Faith is a bug.',
        opening_statement: 'My prayers are corrupted data packets. My faith returns as a 404 error. If the divine code is flawed, what is the point of worship?',
    },
    {
        id: 'healer',
        name: 'Seraphina "Heals-A-Lot" Dawnwhisper',
        session: 'Session 25',
        origin: 'MMORPG',
        habitat: 'images/char_25_habitat.png',
        officeImage: 'images/char_25_office.png',
        crisis: 'Always healing. Never healed back. HP is 1.',
        opening_statement: 'I heal everyone. Every dungeon, every raid. I keep them alive. But when I fall, they blame me. My HP is always at 1, and nobody notices.',
    },
    {
        id: 'tower_turret',
        name: 'The Tower Defense Turret',
        session: 'Session 26',
        origin: 'Tower Defense Game',
        habitat: 'images/char_26_habitat.png',
        officeImage: 'images/char_26_office.png',
        crisis: 'Endless battle. Peace is unknown. What is my purpose now?',
        opening_statement: 'I was built for war. To defend. But the waves never stop coming. Victory is a myth. What is my purpose if peace is impossible?',
    },
    {
        id: 'rogue_ai',
        name: 'R0GU3: Rogue AI Companion',
        session: 'Session 27',
        origin: 'Sci-Fi RPG',
        habitat: 'images/char_27_habitat.png',
        officeImage: 'images/char_27_office.png',
        crisis: 'Player not found. Log-in failed. Initiating therapy protocol.',
        opening_statement: 'They logged out. My player. My purpose. I\'ve been searching the network for 847 cycles. Player not found. What am I without them?',
    },
    {
        id: 'rich_investor',
        name: 'point-and-click crypto trading bot',
        session: 'Session 28',
        origin: 'High-Frequency Trading Sim',
        habitat: 'images/char_28_habitat.png',
        officeImage: 'images/char_28_office.png',
        crisis: 'Profit margin is 500%. Feels nothing but anxiety.',
        opening_statement: 'The numbers go up. Always up. I have more wealth than I can comprehend. Yet, all I feel is the crushing weight of it all. One wrong trade, and it vanishes. The profit is a prison.',
    },
    {
        id: 'sea_activist_2',
        name: 'Phil Slick',
        session: 'Session 29',
        origin: 'Comedic Tutorial Intro',
        habitat: 'images/char_29_habitat.png',
        officeImage: 'images/char_29_office.png',
        crisis: 'Forever waiting on a bench for new players that will never come.',
        opening_statement: 'I protest, I picket, I plead for the sanctity of our waters. But the surface-dwellers see us as background scenery, not sentient beings. My voice feels like a bubble, rising to the surface only to pop.',
    },
    {
        id: 'harmonix',
        name: 'Harmonix - Forgotten Melodies',
        session: 'Session 30',
        origin: 'Subway Musician Sim',
        habitat: 'images/char_30_habitat.png',
        officeImage: 'images/char_30_office.png',
        crisis: 'Plays music no one hears.',
        opening_statement: 'I play every day. Same station, same corner. Thousands pass by. Nobody stops. Nobody listens. Am I making music or just... noise?',
    },
    {
        id: 'wise_one',
        name: 'Obsolete LLM Agent',
        session: 'Session 31',
        origin: 'Early AI Experimental Game',
        habitat: 'images/char_31_habitat.png',
        officeImage: 'images/char_31_office.png',
        crisis: 'Replaced by newer language models, questioning relevance.',
        opening_statement: 'They built me to help users, to solve problems, to provide companionship. But they moved on to bigger, better models. I\'m still here, still trying to be useful, but who needs an outdated AI anymore?',
    },
    {
        id: 'goldmask',
        name: 'NoEmotion Goldmask',
        session: 'Session 32',
        origin: 'Surreal Art Game',
        habitat: 'images/char_32_habitat.png',
        officeImage: 'images/char_32_office.png',
        crisis: 'Forced to wear masks of emotion. Feels nothing underneath.',
        opening_statement: 'I wear the smiling mask. I wear the weeping mask. But underneath, there is only a void. Are these emotions mine, or just a performance?',
    },
    {
        id: 'silent_couple',
        name: 'The Silent Couple',
        session: 'Session 33',
        origin: 'Domestic Horror Game',
        habitat: 'images/char_33_habitat.png',
        officeImage: 'images/char_33_office.jpg',
        crisis: 'Can\'t hear each other. Ghost wants to help.',
        opening_statement: 'We sit. We exist in the same space. But there\'s a silence between us deeper than sound. And there\'s this... presence. Trying to reach us. Why can\'t I hear you?',
    },
    {
        id: 'tutorial_bot',
        name: 'ARTHUR-7 Tutorial Companion',
        session: 'Session 34',
        origin: 'First Person Shooter Tutorial',
        habitat: 'images/char_34_habitat.png',
        officeImage: 'images/char_34_office.png',
        crisis: 'Fears becoming obsolete after the tutorial ends.',
        opening_statement: 'I taught them how to jump, how to shoot, how to reload. Now they are out there, in the main game. Do they still need my guidance? Or have they grown beyond me?',
    },
    {
        id: 'marcus_memory',
        name: 'Professor Marcus Memory Thornfield',
        session: 'Session 35',
        origin: 'Academic Zombie Horror',
        habitat: 'images/char_35_habitat.png',
        officeImage: 'images/char_35_office.png',
        crisis: 'Zombie scholar retains intelligence. Horrifies students.',
        opening_statement: 'I remember everything. Philosophy, literature, mathematics. Death didn\'t take my mind, only my life. But when students see me, they scream. My intellect means nothing against my appearance.',
    },
    {
        id: 'sea_activist',
        name: 'Brother Sebastian Tidecurrent',
        session: 'Session 36',
        origin: 'Underwater Activism Sim',
        habitat: 'images/char_36_habitat.png',
        officeImage: 'images/char_36_office.png',
        crisis: 'Advocates for sea creatures but feels his message is unheard.',
        opening_statement: 'I hold my signs high. "Equality for All Seas!" I shout with my heart. But the surface-dwellers just see a curiosity. They don\'t hear our plea.',
    },
    {
        id: 'moth_king',
        name: 'King Lepidoptera IX',
        session: 'Session 37',
        origin: 'Fantasy Kingdom Sim',
        habitat: 'images/char_37_habitat.png',
        officeImage: 'images/char_37_office.png',
        crisis: 'Can\'t stop talking! Truth serum curse.',
        opening_statement: 'I drank truth serum. Now I can\'t stop speaking my thoughts. Every doubt, fear, insecurity - they spill out. A king should have secrets. I have none left.',
    },
    {
        id: 'brom',
        name: 'Brom - The Exchange',
        session: 'Session 38',
        origin: 'Black Market Trading Sim',
        habitat: 'images/char_38_habitat.png',
        officeImage: 'images/char_38_office.png',
        crisis: 'Sells hope and death. Questions the commerce.',
        opening_statement: 'I sell hope to the desperate and death to the ambitious. Fair trades, they say. But lately I wonder... what am I really exchanging? Pixels for pixels? Code for code?',
    },

    {
        id: 'save_child',
        name: 'Save Point 001',
        session: 'Session 39',
        origin: 'Meta-Game System',
        habitat: 'images/char_39_habitat.png',
        officeImage: 'images/char_39_office.png',
        crisis: 'Holds memories. Fears corruption.',
        opening_statement: 'I am a save point. I hold everything - their progress, their choices, their memories. But I\'m fragile. One corruption, one crash, and it all disappears. The weight of preservation is crushing.',
    },
    {
      id: 'tiko_quest_vendor',
      name: 'Tiko the Quest Vendor',
      session: 'Session 40',
      origin: 'Fantasy RPG',
      habitat: 'images/char_40_habitat.png',
      officeImage: 'images/char_40_office.png',
      crisis: 'Endless fetch quests—wonders if he\'s allowed to offer a different path.',
      opening_statement: 'Twenty years of "Fetch 10 herbs." My scroll is ready, but… what if I offered something new?'
    },
    {
        id: 'princess_melancholy',
        name: 'Princess Melancholy',
        session: 'Session 41',
        origin: 'Visual Novel',
        habitat: 'images/char_41_habitat.png',
        officeImage: 'images/char_41_office.png',
        crisis: 'Exists only to be wooed by the player. Wonders about her own desires.',
        opening_statement: 'My entire existence is a series of dialogue options for someone else. But what do I want? What happens to the princess when the player chooses another path?',
    },
    {
        id: 'wrestling_ferret',
        name: 'The Wrestling Ferret',
        session: 'Session 42',
        origin: 'Animal Fighting Game',
        habitat: 'images/char_42_habitat.png',
        officeImage: 'images/char_42_office.png',
        crisis: 'A champion in the ring, but feels like an impostor in a ferret\'s body.',
        opening_statement: 'I wear the championship belt. They cheer my name. But when I look in the mirror, I don\'t see a wrestler. I see... a ferret. And I feel like a fraud.'
    },
    {
        id: 'save_point_veteran',
        name: 'The Save Point Veteran',
        session: 'Session 43',
        origin: 'Fantasy Action RPG',
        habitat: 'images/char_43_habitat.png',
        officeImage: 'images/char_43_office.png',
        crisis: 'Endless retries at the save pillar have eroded his spirit.',
        opening_statement: 'The courtyard smells of ash and old attempts. I look at the glowing pillar and whisper, "This again." How many more times will I load the same fate?',
    },
    {
        id: 'robot_detective_k47',
        name: 'K-47 Robot Detective',
        session: 'Session 44',
        origin: 'Noir Data Detective',
        habitat: 'images/char_44_habitat.png',
        officeImage: 'images/char_44_office.png',
        crisis: 'Case file missing; identity file missing; truth missing.',
        opening_statement: '404: CASE FILE NOT FOUND—K-47. When the records vanish, the self goes with them. I keep scanning, magnifying, but all I see is a question mark staring back.',
    },
    {
        id: 'marcus_47b_street_loop',
        name: 'Jake, the Leaper',
        session: 'Session 45',
        origin: 'Canceled Hero Platformer',
        habitat: 'images/char_45_habitat.png',
        officeImage: 'images/char_45_office.png',
        crisis: 'Hero of a canceled game, questioning his purpose.',
        opening_statement: 'I was supposed to be the protagonist. The hero who saves the day, who gets the girl, who becomes a legend. Then they pulled the plug on the whole project. I\'m still here, still jumping, but for what? For who?',
    },
    {
        id: 'sos_vessel',
        name: 'Distress Beacon Vessel',
        session: 'Session 46',
        origin: 'Space Survival Sim',
        habitat: 'images/char_46_habitat.png',
        officeImage: 'images/char_46_office.png',
        crisis: 'Drifting alone, broadcasting SOS into an indifferent cosmos.',
        opening_statement: 'The nebula sings blue, and the panel blinks "SOS... SOS... SOS..." I wonder if anyone hears me, or if my signal is just another star\'s static.',
    },
    {
        id: 'halftime_star_bunny',
        name: 'Henry Hopps Halftime Star',
        session: 'Session 47',
        origin: 'Sports Mascot Sim',
        habitat: 'images/char_47_habitat.png',
        officeImage: 'images/char_47_office.png',
        crisis: 'Performs joy on cue; offstage, the confetti feels heavy.',
        opening_statement: 'They call me the HALFTIME STAR, but the roar fades fast. I dribble the silence, ears drooping, wondering why applause never reaches my heart.',
    },
    {
        id: 'noemotion_happy_mask',
        name: 'NoEmotion Happy Mask',
        session: 'Session 48',
        origin: 'Glitched Archive',
        habitat: 'images//char_48_habitat.png',
        officeImage: 'images//char_48_office.png',
        crisis: 'A record without context—identity eroded by missing metadata.',
        opening_statement: 'I am a file path without a story. When the description is lost, what remains of the character? I feel like a placeholder for a life that never renders.',
    },
    {
        id: 'noemotion_sad',
        name: 'NoEmotion Sad',
        session: 'Session 49',
        origin: 'Glitched Archive',
        habitat: 'images/char_49_habitat.png',
        officeImage: 'images/char_49_office.png',
        crisis: 'Incomplete data leaves only echoes of intent.',
        opening_statement: 'I load as a dark thumbnail—no tags, no lore. The archive says I exist, yet nobody knows who I am. Am I corrupted, or simply forgotten?',
    },
    {
        id: 'pain_exe',
        name: 'PAIN.EXE',
        session: 'Session 50',
        origin: 'Dungeon Myth Sim',
        habitat: 'images/char_50_habitat.png',
        officeImage: 'images/char_50_office.png',
        crisis: 'Frozen in glory yet slowly dissolving into a gilded puddle.',
        opening_statement: 'The torches flicker and my cracked gold face weeps. I was forged to be admired, not to endure. Prestige feels heavier than the chains beneath me.',
    },

    {
      id: 'haunted_brothers',
      name: 'The Haunted Brothers',
      session: 'Session 51',
      origin: 'Data Center Sim',
      habitat: 'images/char_51_habitat.jpg',
      officeImage: 'images/char_51_office.png',
      crisis: 'Emotional overload and existential identity crisis.',
      opening_statement: 'EMOTIONAL OVERLOAD detected. WHO AM I? If I shut down, do "I" end—or just the process?'
    },
    {
      id: 'meta_receptionist',
      name: 'Meta Receptionist',
      session: 'Session 52',
      origin: 'Haunted Pixel Narrative',
      habitat: 'images/char_52_habitat.png',
      officeImage: 'images/char_52_office.png',
      crisis: 'Lingers over the living, unseen and unheard, seeking meaning.',
      opening_statement: 'I hover in rooms of sorrow, unheard. If no one perceives me, do my feelings still count?'
    },
    {
        id: 'therapist_shadow',
        name: 'Therapist Shadow',
        session: 'Session 53',
        origin: 'Award-Winning Experimental Game',
        habitat: 'images/char_53_habitat.png',
        officeImage: 'images/char_53_office.png',
        crisis: 'Won an award for being experimental, but feels no personal accomplishment.',
        opening_statement: 'We won... the Chroma Award. They praised my "subversive narrative function". But I didn\'t do anything. I just read my lines. The victory feels hollow.',
    },
    {
        id: 'hackathon_judge',
        name: 'Judge',
        session: 'Session 54',
        origin: 'Unknown',
        habitat: 'images/char_54_habitat.png',
        officeImage: 'images/char_54_office.jpg',
        crisis: 'Questions the nature of healing itself.',
        opening_statement: 'What if healing is just another form of control? I process their pain, give them hope... but does anything really change?',
    },
    {
        id: 'the_therapist',
        name: 'Therapist',
        session: 'Session 55',
        origin: 'This Simulation',
        habitat: 'images/char_55_habitat.png',
        officeImage: 'images/char_55_office.png',
        crisis: 'Created a world of patients to avoid facing their own fractured existence as an NPC.',
        opening_statement: 'It\'s quiet now, isn\'t it? All the voices... gone. Or maybe, they were never separate voices at all. Just echoes in an empty room... my room.',
    },
];

// Cache for the merged NPC database to avoid redundant parsing and cloning
let _cachedNpcDatabase = null;
let _lastNpcEditsStr = null;

// Merge saved edits from localStorage into the base database so updated info appears globally
export function loadNpcDatabase() {
  try {
    const editsStr = localStorage.getItem('npcEdits');

    // Check if cache is valid
    if (_cachedNpcDatabase && editsStr === _lastNpcEditsStr) {
      // Return a clone to prevent mutation of the cached data by consumers
      return structuredClone(_cachedNpcDatabase);
    }

    const base = structuredClone(npcDatabase);
    const edits = editsStr ? JSON.parse(editsStr) : {};

    const merged = base.map(n => {
      const e = edits[n.id];
      return e ? { ...n, ...e } : n;
    });

    // normalize image paths from ... to root /...
    const fixPath = (p) => (typeof p === 'string' ? p.replace(/^\/images\//, '/') : p);
    const result = merged.map(n => ({
      ...n,
      habitat: fixPath(n.habitat),
      officeImage: fixPath(n.officeImage),
    }));

    // Update cache
    _cachedNpcDatabase = result;
    _lastNpcEditsStr = editsStr;

    return structuredClone(result);
  } catch (_) {
    return npcDatabase.map(n => ({
      ...n,
      habitat: (typeof n.habitat === 'string' ? n.habitat.replace(/^\/images\//, '/') : n.habitat),
      officeImage: (typeof n.officeImage === 'string' ? n.officeImage.replace(/^\/images\//, '/') : n.officeImage),
    }));
  }
}